# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-24 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_auto_20190423_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oauthqquser',
            options={'verbose_name': 'qq用户登陆信息', 'verbose_name_plural': 'qq用户登陆信息'},
        ),
        migrations.AlterModelTable(
            name='oauthqquser',
            table='tb_oauth_qq',
        ),
    ]
